@startuml
scale 500 width

note "Voucher status flow" as N1

[*] --> ACTIVE : uploadVouchers()

ACTIVE --> RESERVED : reserveVoucher()
ACTIVE --> PURCHASED : purchaseVoucher()

RESERVED --> ACTIVE : reservationExpired()
RESERVED --> ACTIVE : cancelReservation()
RESERVED --> PURCHASED : confirmReservation()
PURCHASED --> REDEEMED : redeemVouchers()

ACTIVE --> INACTIVE : voucherExpired()
RESERVED --> INACTIVE : voucherExpired()

@enduml
